PlantGram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("plants.urls")),
    path('accounts/', include('allauth.urls')),
]

plants/urls.py
from . import views
from django.urls import path
from .views import AddPostView 

app_name = 'plants'

urlpatterns = [
    path('', views.LandingView.as_view(), name='home'),
    path('?P<slug>[\w-]+/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
    path('add_post/', views.AddPostView.as_view(), name='add_post'),
    path('list_view/', views.PostListView.as_view(), name='list_view')
]

plants/models.py
from django.db import models, IntegrityError
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import random


from cloudinary.models import CloudinaryField
from cloudinary.forms import CloudinaryFileField   
from cloudinary import CloudinaryImage


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    featured_image = CloudinaryField('image', default='placeholder')
    description = models.TextField()
    title = models.TextField(default="placeholder")
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='blog_likes', blank=True)
    slug = models.SlugField(max_length=200, null=True, unique=True)

    def save(self, *args, **kwargs):
        try:
            self.slug = ''.join(str(random.randint(0, 9)) for _ in range(8))
            super().save(*args, **kwargs)
        except IntegrityError:
            self.save(*args, **kwargs)

    def number_of_likes(self):
        return self.likes.count()

    def date(self):
        return self.created_on.date()

    def get_absolute_url(self):
        return reverse('plants:post_detail', args=[self.slug])

    def __str__(self):
        return f'{self.title}'



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = CloudinaryField('profile_image', default='placeholder')

    def __str__(self):
        return f'{self.user.username} Profile'

class Picture(models.Model):
    image = CloudinaryField('image')

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

plants/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

	class Meta:
		model = Post	
		fields = ('description', 'title', 'featured_image')

		widgets = {
			'description': forms.TextInput(attrs={'class': 'form-control'}),
			'title': forms.TextInput(attrs={'class': 'form-control'}),
		}

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('body',)

plants/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.views.generic import CreateView, DetailView
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from cloudinary.forms import cl_init_js_callbacks

from django.views.generic import (
    ListView
)
from .models import Post
from.forms import PostForm, CommentForm


class LandingView(ListView):
    queryset = Post.objects
    context_object_name = "landing"
    template_name = "index.html"


class PostListView(ListView):
    queryset = Post.objects.order_by('-created_on')
    context_object_name = "posts"
    template_name = 'list_view.html'

    def comment_view(self,request, slug):
        queryset = Post.objects
        post = get_object_or_404(queryset, slug=slug)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST or None)
            if comment_form.is_valid():
                content = request.POST.get('content')
                comment.objects.create(post=post, user=request.user, content=content)
                comment.save()
                return HttpResponseRedirect('plants: list_view')
                    
        else:
            comment_form = CommentForm()
        return render(request, 'plants: list_view', {
            'comments': comments,
        })


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )
    
    def post(self, request, slug, *args, **kwargs):
        queryset = Post.objects
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )


class PostLike(View):

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('plants:post_detail', args=[slug]))


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            post_form = PostForm(request.POST, request.FILES)

            if post_form.is_valid():
                post_form.instance.author = request.user
                postform = post_form.save(commit=False)
                postform.save()

            return HttpResponseRedirect(reverse('plants:list_view'))

templates/add_post.html
{% extends 'base.html' %}
{% block title %}Create A New Blog Post!{% endblock %}
{% block content %}

    
{% if user.is_authenticated %}
	<h1>Add Post...</h1>
	<br/><br/>
	{% load cloudinary %}
	<div class="form-group">
<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.media }}
			{{ form.as_p }}
			<button type="submit" class="btn btn-secondary">Post</button>
	</div>

{% else %}

You're not allowed here! (and you know it...)

{% endif %}



{% endblock %}

templates/base.html
{% load static %}
{% load cloudinary_static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Planda</title>
    <link rel="icon" type="image/x-icon"
        href="https://raw.githubusercontent.com/DazHaze/PlantGram/main/media/leaf-16.ico?token=GHSAT0AAAAAABT6V2KLHJEGFVYBCLLX23TMYTZVGRA">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/966dc3bd5a.js" crossorigin="anonymous"></script>
</head>

<body style="padding-top: 56px;">
    <nav class="navbar navbar-expand-sm navbar-light autohide">
        <div class="container-fluid">
            <a href="{%  url 'plants:home'  %}" class="navbar-brand mb-0 h1">
                Planda
            </a>

            <button type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" class="navbar-toggler"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a href="{%  url 'plants:list_view'  %}" class="nav-link">
                            Home
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a href="{% url 'plants:add_post' %}" class="nav-link">
                            <i class="fas fa-plus" style="color:black; font-size:1.5rem;"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <img src="https://w7.pngwing.com/pngs/304/275/png-transparent-user-profile-computer-icons-profile-miscellaneous-logo-monochrome-thumbnail.png"
                            class="Instagram-card-user-image" alt="">
                    </li>
                    <li class="nav-item active">
                        <p class="nav-link">{{user.username}}</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <script>
        document.addEventListener("DOMContentLoaded", function () {

            nav_autohide = document.querySelector('.autohide');
            navbar_height = document.querySelector('.navbar').offsetHeight;
            document.body.style.paddingTop = navbar_height + 'px';

            if (nav_autohide) {
                var last_scroll_top = 0;
                window.addEventListener('scroll', function () {
                    let scroll_top = window.scrollY;
                    if (scroll_top < last_scroll_top) {
                        nav_autohide.classList.remove('scrolled-down');
                        nav_autohide.classList.add('scrolled-up');
                    } else {
                        nav_autohide.classList.remove('scrolled-up');
                        nav_autohide.classList.add('scrolled-down');
                    }
                    last_scroll_top = scroll_top;
                });
            }
        });
    </script>

    <style>
        .scrolled-down {
            transform: translateY(-100%);
            transition: all 0.3s ease-in-out;
        }

        .scrolled-up {
            transform: translateY(0);
            transition: all 0.3s ease-in-out;
        }

        .autohide {
            position: fixed;
            top: 0;
            right: 0;
            left: 0;
            width: 100%;
            z-index: 1030;
        }
    </style>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        {% endblock content %}
    </main>

    <footer>
        Copyright Darragh Hayes 2022
    </footer>
</body>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Planda</title>
    <link rel="icon" type="image/x-icon"
        href="https://raw.githubusercontent.com/DazHaze/PlantGram/main/media/leaf-16.ico?token=GHSAT0AAAAAABT6V2KLHJEGFVYBCLLX23TMYTZVGRA">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-latest.js"></script>
    <script src="https://kit.fontawesome.com/966dc3bd5a.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

    <style>
        * {
            padding: 0;
            margin: 0;
        }

        .splash-image {
            background-repeat: no-repeat;
            background-size: cover;
            height: 100vh;
        }
    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="row splash-image"
            style="background-image: url('https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1174&q=80'); height:100vh; box-shadow: inset 0 0 100px black; position: relative;">
            <div class="col-sm d-block d-md-none h-100 d-flex justify-content-center align-items-center">
                <div style="background: rgba(117,117,117,0.3); padding:3rem; border-radius: 0.3rem;">
                    <div class="d-flex" style="padding: 1rem; border-left: 5px solid orange">
                        <h1 style="color: white;">Welcome to</h1>
                        <h1 style="padding-left: 1rem; text-transform: uppercase; font-family: 'Poppins';"> Planda
                        </h1>
                        <i class="fas fa-leaf" style="color: green;"></i>
                    </div>
                    <div class="d-flex flex-column justify-content-center align-items-center">
                        <form action="{% url 'account_login' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary" style="
                        background-color: orange !important; 
                        border:1px solid orange !important; 
                        color:white  !important;
                        ">
                        </form>

                        Login</button>
                        <p style="color:white; padding:1rem; font-size:0.7rem;">Not a member of the Planda community
                            yet? <a href="{% url 'account_signup' %}" style="margin: 0.5rem; color: slategrey;">Register
                                now</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg d-none d-md-flex h-100 justify-content-center align-items-center">
                <div style="background: rgba(117,117,117,0.3); padding:3rem; border-radius: 0.3rem;">
                    <div class="d-flex" style="padding: 1rem; border-left: 5px solid orange">
                        <h1 style="color: white;">Welcome to</h1>
                        <h1 style="padding-left: 1rem; text-transform: uppercase; font-family: 'Poppins';"> planda
                        </h1>
                        <i class="fas fa-leaf" style="color: green;"></i>
                    </div>
                    <div class="d-flex flex-column justify-content-center align-items-center">
                        <form action="{% url 'account_login' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary" style="
                        background-color: orange !important; 
                        border:1px solid orange !important; 
                        color:white  !important;
                        ">
                        </form>

                        Login</button>
                        <p style="color:white; padding:1rem; font-size:0.7rem;">Not a member of the Planda community
                            yet? <a href="{% url 'account_signup' %}" style="margin: 0.5rem; color: slategrey;">Register
                                now</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>

<footer style="
  color: white;
  position: fixed;
  padding: 10px 10px 0px 10px;
  bottom: 0;
  width: 100%;
  /* Height of the footer*/ 
  height: 40px;
  text-align: center;
">
    Copyright Darragh Hayes 2022
</footer>

</html>

templates/list_view.html
{% extends "base.html" %}

{% block content %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>

    </style>

</head>

<body>
    {% for post in posts %}
    <div class="Instagram-card">
        <div class="Instagram-card-header">
            {% if "placeholder" in post.author.profile.image.url %}
            <img src="https://w7.pngwing.com/pngs/304/275/png-transparent-user-profile-computer-icons-profile-miscellaneous-logo-monochrome-thumbnail.png"
                class="Instagram-card-user-image" alt="">
            {% else %}
            <img src="{{ post.author.profile.image.url }}" class="Instagram-card-user-image" alt="">
            {% endif %}
            <a class="Instagram-card-user-name" href="https://www.instagram.com/rogersbase/"> {{ post.author }} </a>
            <p class="Instagram-card-time"> {{post.date}} </p>
        </div>
        <div style="
        width: 100%;
        text-align:center;
        ">
            <h3>{{post.title}}</h3>
        </div>
        <div class="Instagram-card-image">
            <a href="{% url 'plants:post_detail' post.slug  %}">
                <img src="{{ post.featured_image.url}}" height="600px" alt=""
                    style="border-bottom: 2px dotted orange ;">
            </a>
        </div>

        <div class="Instagram-card-content">
            <p class="Likes">{{ post.number_of_likes}} likes</p>
            <p><a class="Instagram-card-content-user">
                    {{ post.author }}
                </a>
                {{ post.description }} <p class="background-text">
                    {{ post.created_on }}</p>
            </p>
            {% if not post.comments.all %}
            <p class="text-muted">No Comments yet ...</p>
            {% else %}
            {% for comment in post.comments.all %}
            <div class="user-comment">
                <p>{{ comment.name }}</p>
                <p>&nbsp;-&nbsp; </p>
                <p>{{ comment.body }}&nbsp; </p>
                <p style="font-style:italic; color:lightgray;">{{ comment.created_on }}</p>
            </div>
            {% endfor %}
            {% endif %}
        </div>

        <div class="Instagram-card-footer d-flex justify-content-around">
            <strong>
                {% if user.is_authenticated %}
                <form class="footer-action-icons" action="{% url 'plants:post_like' post.slug %}" method="post">
                    {% csrf_token %}
                    {% if liked %}
                    <button type="submit" name="blogpost_id" value="{{ post.slug}}" class="form-submit-button"><i
                            class="fa fa-heart footer-action-icons"></i></button>
                    {% else %}
                    <button type="submit" name="blogpost_id" value="{{ post.slug}}" class="form-submit-button"><i
                            class="fa fa-heart footer-action-icons" style="color:grey !important;"></i></button>
                    {% endif %}
                </form>
                {% else %}
                <span><i class="fa fa-heart footer-action-icons" style="color:grey !important;"></i></span>
                {% endif %}
            </strong>
            <a href="{% url 'plants:post_detail' post.slug  %}" class="footer-action-icons a-link">Leave a
                comment...</a>
            <a class="footer-action-icons" href="#"><i class="fa fa-ellipsis-h"></i></a>
        </div>

    </div>
    {% endfor %}
</body>

</html>
{%endblock%}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <h1 class="post-title">{{ post.caption }}</h1>
                <div style="display:flex; width:100%;">
                    {% if "placeholder" in post.author.profile.image.url %}
                    <img src="https://w7.pngwing.com/pngs/304/275/png-transparent-user-profile-computer-icons-profile-miscellaneous-logo-monochrome-thumbnail.png"
                        class="Instagram-card-user-image" alt="">
                    {% else %}
                    <img src="{{ post.author.profile.image.url }}" class="Instagram-card-user-image" alt="">
                    {% endif %}
                    <p class="Instagram-card-user-name" style="color:black !important;">{{ post.author }}</p>
                </div>
                <p>{{post.created_on}}</p>
                <p class="card-text ">
                    {{ post.description }}
                </p>
                {% if not post.comments.all %}
                <p>No Comments yet ...</p>
                {% else %}
                {% for comment in post.comments.all %}
                <div class="user-comment">
                    <p>{{ comment.name }}</p>
                    <p>&nbsp;-&nbsp; </p>
                    <p>{{ comment.body }}&nbsp; </p>
                    <p style="font-style:italic; color:lightgray;">{{ comment.created_on }}</p>
                </div>
                {% endfor %}
                {% endif %}
                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <form method="post" style="margin-top: 1.3rem;">
                    {% csrf_token %}
                    {{ comment_form | crispy}}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>

                {% endif %}
                <div class="row">
                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="footer-action-icons d-flex" action="{% url 'plants:post_like' post.slug %}"
                                method="post">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{ post.slug}}"
                                    class="form-submit-button"><i class="fa fa-heart footer-action-icons"></i></button>
                                <p style="color:black; padding-top: 1rem;" class="text-muted">{{post.number_of_likes}}
                                </p>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{ post.slug}}"
                                    class="form-submit-button"><i class="fa fa-heart footer-action-icons"
                                        style="color:grey !important;"></i></button>
                                <p style="color:black; padding-top: 1rem;" class="text-muted">{{post.number_of_likes}}
                                </p>
                                {% endif %}
                            </form>
                            {% else %}
                            <span><i class="fa fa-heart footer-action-icons" style="color:grey !important;"></i></span>
                            {% endif %}
                        </strong>
                    </div>
                </div>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src=" {{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col mb-4  mt-3 left  top">
            <div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col" style="border-top: 2px dotted orange">
        </div>
    </div>

</div>

{% endblock content %}